### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by pradeepjairamani** [snyk/serverless-goof-gcf#7]
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "create"...
Serverless: Compiling function "list"...
Serverless: Compiling function "get"...
Serverless: Compiling function "update"...
Serverless: Compiling function "delete"...
Serverless: Compiling function "render"...
Serverless: Compiling function "internalBackup"...
Serverless: Compiling function "internalRestore"...
Serverless: Compiling function "adminApi"...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...
.......... 
  Error --------------------------------------------------
 
  Error: Deployment failed: RESOURCE_ERROR
  
       {"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"400","ResourceErrorMessage":"Build failed: exit status 1\n\n> protobufjs@6.9.0 postinstall /workspace/node_modules/protobufjs\n> node scripts/postinstall\n\n\n> core-js@2.6.11 postinstall /workspace/node_modules/core-js\n> node -e \"try{require('./postinstall')}catch(e){}\"\n\n\n> grpc@1.24.3 install /workspace/node_modules/grpc\n> node-pre-gyp install --fallback-to-build --library=static_library\n\nmodule.js:478\n    throw err;\n    ^\n\nError: Cannot find module '../'\n    at Function.Module._resolveFilename (module.js:476:15)\n    at Function.Module._load (module.js:424:25)\n    at Module.require (module.js:504:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/workspace/node_modules/.bin/node-pre-gyp:15:20)\n    at Module._compile (module.js:577:32)\n    at Object.Module._extensions..js (module.js:586:10)\n    at Module.load (module.js:494:32)\n    at tryModuleLoad (module.js:453:12)\n    at Function.Module._load (module.js:445:3)\n\nnpm ERR! Linux 5.0.0-1034-gcp\nnpm ERR! argv \"/nodejs/bin/node\" \"/nodejs/bin/npm\" \"rebuild\" \"--update-binary\"\nnpm ERR! node v6.17.0\nnpm ERR! npm  v3.10.10\nnpm ERR! code ELIFECYCLE\nnpm ERR! grpc@1.24.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the grpc@1.24.3 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the grpc package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     node-pre-gyp install --fallback-to-build --library=static_library\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs grpc\nnpm ERR! Or if that isn't available, you can get their info via:\nnpm ERR!     npm owner ls grpc\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /workspace/npm-debug.log\n"}
      at throwErrorIfDeploymentFails (/opt/serverless-goof-gcf/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:71:11)
      at provider.request.then.response (/opt/serverless-goof-gcf/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:42:17)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Framework Version:         1.72.0
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.12

**Comment by pradeepjairamani** [comment]
Gcloud function log

Build failed: exit status 1 > protobufjs@6.9.0 postinstall /workspace/node_modules/protobufjs > node scripts/postinstall > core-js@2.6.11 postinstall /workspace/node_modules/core-js > node -e "try{require('./postinstall')}catch(e){}" > grpc@1.24.3 install /workspace/node_modules/grpc > node-pre-gyp install --fallback-to-build --library=static_library module.js:478 throw err; ^ Error: Cannot find module '../' at Function.Module._resolveFilename (module.js:476:15) at Function.Module._load (module.js:424:25) at Module.require (module.js:504:17) at require (internal/module.js:20:19) at Object.<anonymous> (/workspace/node_modules/.bin/node-pre-gyp:15:20) at Module._compile (module.js:577:32) at Object.Module._extensions..js (module.js:586:10) at Module.load (module.js:494:32) at tryModuleLoad (module.js:453:12) at Function.Module._load (module.js:445:3) npm ERR! Linux 5.0.0-1034-gcp npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "rebuild" "--update-binary" npm ERR! node v6.17.0 npm ERR! npm v3.10.10 npm ERR! code ELIFECYCLE npm ERR! grpc@1.24.3 install: `node-pre-gyp install --fallback-to-build --library=static_library` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the grpc@1.24.3 install script 'node-pre-gyp install --fallback-to-build --library=static_library'. npm ERR! Make sure you have the latest version of node.js and npm installed. npm ERR! If you do, this is most likely a problem with the grpc package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR! node-pre-gyp install --fallback-to-build --library=static_library npm ERR! You can get information on how to open an issue for this project with: npm ERR! npm bugs grpc npm ERR! Or if that isn't available, you can get their info via: npm ERR! npm owner ls grpc npm ERR! There is likely additional logging output above. npm ERR! Please include the following file with any support request: npm ERR! /workspace/npm-debug.log
